import { mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * Seed Chart of Accounts - Standar Indonesia + Custom Petshop
 * 
 * Struktur Numbering:
 * 1-xxx = ASSET (Aset)
 * 2-xxx = LIABILITY (Kewajiban)
 * 3-xxx = EQUITY (Ekuitas)
 * 4-xxx = REVENUE (Pendapatan)
 * 5-xxx = EXPENSE (Beban)
 */

export const seedChartOfAccounts = mutation({
  args: {},
  returns: v.object({
    message: v.string(),
    accountCount: v.number(),
  }),
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("accounts").first();
    if (existing) {
      throw new Error("Chart of Accounts already seeded. Delete all accounts first.");
    }

    const accounts = [
      // ==================== 1-xxx ASSETS ====================
      // Level 1: Main Category
      {
        accountCode: "1-000",
        accountName: "ASET",
        accountType: "ASSET",
        category: "Main",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 1,
        parentId: null,
      },

      // Level 2: Current Assets
      {
        accountCode: "1-100",
        accountName: "Aset Lancar",
        accountType: "ASSET",
        category: "Current Asset",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 2,
        parentCode: "1-000",
      },
      {
        accountCode: "1-101",
        accountName: "Kas Besar",
        accountType: "ASSET",
        category: "Cash",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-100",
        description: "Uang tunai di tangan (petty cash)",
      },
      {
        accountCode: "1-102",
        accountName: "Kas Kecil",
        accountType: "ASSET",
        category: "Cash",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-100",
        description: "Kas kecil operasional harian",
      },
      {
        accountCode: "1-110",
        accountName: "Bank",
        accountType: "ASSET",
        category: "Bank",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 3,
        parentCode: "1-100",
      },
      {
        accountCode: "1-111",
        accountName: "Bank BCA",
        accountType: "ASSET",
        category: "Bank",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-110",
      },
      {
        accountCode: "1-112",
        accountName: "Bank Mandiri",
        accountType: "ASSET",
        category: "Bank",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-110",
      },
      {
        accountCode: "1-113",
        accountName: "Bank BRI",
        accountType: "ASSET",
        category: "Bank",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-110",
      },
      {
        accountCode: "1-120",
        accountName: "Piutang Usaha",
        accountType: "ASSET",
        category: "Accounts Receivable",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-100",
        description: "Piutang dari penjualan kredit",
      },
      {
        accountCode: "1-121",
        accountName: "Piutang Lain-lain",
        accountType: "ASSET",
        category: "Other Receivables",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-100",
      },
      {
        accountCode: "1-130",
        accountName: "Persediaan Barang Dagangan",
        accountType: "ASSET",
        category: "Inventory",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 3,
        parentCode: "1-100",
      },
      {
        accountCode: "1-131",
        accountName: "Persediaan Makanan Hewan",
        accountType: "ASSET",
        category: "Inventory - Pet Food",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-130",
        description: "Stok makanan anjing, kucing, burung, ikan",
      },
      {
        accountCode: "1-132",
        accountName: "Persediaan Aksesoris Hewan",
        accountType: "ASSET",
        category: "Inventory - Accessories",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-130",
        description: "Kalung, mainan, kandang, dll",
      },
      {
        accountCode: "1-133",
        accountName: "Persediaan Obat & Vitamin",
        accountType: "ASSET",
        category: "Inventory - Medicine",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-130",
        description: "Obat-obatan, vitamin, suplemen hewan",
      },
      {
        accountCode: "1-134",
        accountName: "Persediaan Vaksin",
        accountType: "ASSET",
        category: "Inventory - Vaccine",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-130",
        description: "Vaksin rabies, distemper, dll",
      },
      {
        accountCode: "1-135",
        accountName: "Persediaan Grooming Supplies",
        accountType: "ASSET",
        category: "Inventory - Grooming",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 4,
        parentCode: "1-130",
        description: "Shampoo, conditioner, sisir, gunting",
      },
      {
        accountCode: "1-140",
        accountName: "Biaya Dibayar Dimuka",
        accountType: "ASSET",
        category: "Prepaid Expense",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-100",
        description: "Sewa, asuransi, langganan yang dibayar dimuka",
      },

      // Level 2: Fixed Assets
      {
        accountCode: "1-200",
        accountName: "Aset Tetap",
        accountType: "ASSET",
        category: "Fixed Asset",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 2,
        parentCode: "1-000",
      },
      {
        accountCode: "1-201",
        accountName: "Peralatan",
        accountType: "ASSET",
        category: "Equipment",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-200",
        description: "Peralatan grooming, medis, dll",
      },
      {
        accountCode: "1-202",
        accountName: "Furniture & Fixtures",
        accountType: "ASSET",
        category: "Furniture",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-200",
        description: "Meja, kursi, rak display",
      },
      {
        accountCode: "1-203",
        accountName: "Kendaraan",
        accountType: "ASSET",
        category: "Vehicle",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-200",
        description: "Mobil operasional, motor",
      },
      {
        accountCode: "1-204",
        accountName: "Bangunan",
        accountType: "ASSET",
        category: "Building",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "1-200",
      },
      {
        accountCode: "1-210",
        accountName: "Akumulasi Penyusutan",
        accountType: "ASSET",
        category: "Accumulated Depreciation",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 3,
        parentCode: "1-200",
      },
      {
        accountCode: "1-211",
        accountName: "Akumulasi Penyusutan Peralatan",
        accountType: "ASSET",
        category: "Accumulated Depreciation",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "1-210",
      },
      {
        accountCode: "1-212",
        accountName: "Akumulasi Penyusutan Furniture",
        accountType: "ASSET",
        category: "Accumulated Depreciation",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "1-210",
      },
      {
        accountCode: "1-213",
        accountName: "Akumulasi Penyusutan Kendaraan",
        accountType: "ASSET",
        category: "Accumulated Depreciation",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "1-210",
      },

      // ==================== 2-xxx LIABILITIES ====================
      {
        accountCode: "2-000",
        accountName: "KEWAJIBAN",
        accountType: "LIABILITY",
        category: "Main",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 1,
        parentId: null,
      },
      {
        accountCode: "2-100",
        accountName: "Kewajiban Lancar",
        accountType: "LIABILITY",
        category: "Current Liability",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 2,
        parentCode: "2-000",
      },
      {
        accountCode: "2-101",
        accountName: "Hutang Usaha",
        accountType: "LIABILITY",
        category: "Accounts Payable",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 3,
        parentCode: "2-100",
        description: "Hutang kepada supplier",
      },
      {
        accountCode: "2-102",
        accountName: "Hutang Gaji",
        accountType: "LIABILITY",
        category: "Payroll Payable",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 3,
        parentCode: "2-100",
      },
      {
        accountCode: "2-110",
        accountName: "Hutang Pajak",
        accountType: "LIABILITY",
        category: "Tax Payable",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 3,
        parentCode: "2-100",
      },
      {
        accountCode: "2-111",
        accountName: "PPN Keluaran",
        accountType: "LIABILITY",
        category: "VAT Output",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "2-110",
        taxable: true,
        description: "PPN dari penjualan",
      },
      {
        accountCode: "2-112",
        accountName: "PPh 21",
        accountType: "LIABILITY",
        category: "Income Tax Payable",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "2-110",
        taxable: true,
      },
      {
        accountCode: "2-113",
        accountName: "PPh 23",
        accountType: "LIABILITY",
        category: "WHT Payable",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "2-110",
        taxable: true,
      },
      {
        accountCode: "2-200",
        accountName: "Kewajiban Jangka Panjang",
        accountType: "LIABILITY",
        category: "Long-term Liability",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 2,
        parentCode: "2-000",
      },
      {
        accountCode: "2-201",
        accountName: "Hutang Bank",
        accountType: "LIABILITY",
        category: "Bank Loan",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 3,
        parentCode: "2-200",
      },

      // ==================== 3-xxx EQUITY ====================
      {
        accountCode: "3-000",
        accountName: "EKUITAS",
        accountType: "EQUITY",
        category: "Main",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 1,
        parentId: null,
      },
      {
        accountCode: "3-100",
        accountName: "Modal",
        accountType: "EQUITY",
        category: "Capital",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 2,
        parentCode: "3-000",
      },
      {
        accountCode: "3-200",
        accountName: "Laba Ditahan",
        accountType: "EQUITY",
        category: "Retained Earnings",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 2,
        parentCode: "3-000",
        description: "Akumulasi laba dari periode sebelumnya",
      },
      {
        accountCode: "3-300",
        accountName: "Laba Tahun Berjalan",
        accountType: "EQUITY",
        category: "Current Year Earnings",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 2,
        parentCode: "3-000",
        description: "Laba/rugi periode berjalan (temporary)",
      },
      {
        accountCode: "3-400",
        accountName: "Prive",
        accountType: "EQUITY",
        category: "Drawings",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 2,
        parentCode: "3-000",
        description: "Penarikan modal oleh pemilik",
      },

      // ==================== 4-xxx REVENUE ====================
      {
        accountCode: "4-000",
        accountName: "PENDAPATAN",
        accountType: "REVENUE",
        category: "Main",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 1,
        parentId: null,
      },
      {
        accountCode: "4-100",
        accountName: "Pendapatan Usaha",
        accountType: "REVENUE",
        category: "Operating Revenue",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 2,
        parentCode: "4-000",
      },
      {
        accountCode: "4-110",
        accountName: "Pendapatan Penjualan Retail",
        accountType: "REVENUE",
        category: "Retail Sales",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 3,
        parentCode: "4-100",
      },
      {
        accountCode: "4-111",
        accountName: "Penjualan Makanan Hewan",
        accountType: "REVENUE",
        category: "Pet Food Sales",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-110",
        taxable: true,
      },
      {
        accountCode: "4-112",
        accountName: "Penjualan Aksesoris",
        accountType: "REVENUE",
        category: "Accessories Sales",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-110",
        taxable: true,
      },
      {
        accountCode: "4-113",
        accountName: "Penjualan Obat & Vitamin",
        accountType: "REVENUE",
        category: "Medicine Sales",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-110",
        taxable: true,
      },
      {
        accountCode: "4-120",
        accountName: "Pendapatan Jasa Klinik",
        accountType: "REVENUE",
        category: "Clinic Services",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 3,
        parentCode: "4-100",
      },
      {
        accountCode: "4-121",
        accountName: "Jasa Pemeriksaan & Konsultasi",
        accountType: "REVENUE",
        category: "Medical Examination",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-120",
        taxable: true,
      },
      {
        accountCode: "4-122",
        accountName: "Jasa Vaksinasi",
        accountType: "REVENUE",
        category: "Vaccination",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-120",
        taxable: true,
      },
      {
        accountCode: "4-123",
        accountName: "Jasa Sterilisasi",
        accountType: "REVENUE",
        category: "Sterilization",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-120",
        taxable: true,
      },
      {
        accountCode: "4-130",
        accountName: "Pendapatan Jasa Grooming",
        accountType: "REVENUE",
        category: "Grooming Services",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 3,
        parentCode: "4-100",
      },
      {
        accountCode: "4-131",
        accountName: "Grooming Basic",
        accountType: "REVENUE",
        category: "Basic Grooming",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-130",
        taxable: true,
      },
      {
        accountCode: "4-132",
        accountName: "Grooming Premium",
        accountType: "REVENUE",
        category: "Premium Grooming",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 4,
        parentCode: "4-130",
        taxable: true,
      },
      {
        accountCode: "4-140",
        accountName: "Pendapatan Hotel Hewan",
        accountType: "REVENUE",
        category: "Pet Hotel",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 3,
        parentCode: "4-100",
        taxable: true,
        description: "Pendapatan dari penitipan hewan",
      },
      {
        accountCode: "4-200",
        accountName: "Pendapatan Lain-lain",
        accountType: "REVENUE",
        category: "Other Income",
        normalBalance: "CREDIT",
        isHeader: true,
        level: 2,
        parentCode: "4-000",
      },
      {
        accountCode: "4-201",
        accountName: "Pendapatan Bunga",
        accountType: "REVENUE",
        category: "Interest Income",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 3,
        parentCode: "4-200",
      },
      {
        accountCode: "4-202",
        accountName: "Potongan Pembelian",
        accountType: "REVENUE",
        category: "Purchase Discount",
        normalBalance: "CREDIT",
        isHeader: false,
        level: 3,
        parentCode: "4-200",
        description: "Diskon dari supplier",
      },

      // ==================== 5-xxx EXPENSES ====================
      {
        accountCode: "5-000",
        accountName: "BEBAN",
        accountType: "EXPENSE",
        category: "Main",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 1,
        parentId: null,
      },
      {
        accountCode: "5-100",
        accountName: "Harga Pokok Penjualan",
        accountType: "EXPENSE",
        category: "Cost of Goods Sold",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 2,
        parentCode: "5-000",
      },
      {
        accountCode: "5-101",
        accountName: "HPP Makanan Hewan",
        accountType: "EXPENSE",
        category: "COGS - Pet Food",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-100",
      },
      {
        accountCode: "5-102",
        accountName: "HPP Aksesoris",
        accountType: "EXPENSE",
        category: "COGS - Accessories",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-100",
      },
      {
        accountCode: "5-103",
        accountName: "HPP Obat & Vitamin",
        accountType: "EXPENSE",
        category: "COGS - Medicine",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-100",
      },
      {
        accountCode: "5-104",
        accountName: "HPP Vaksin",
        accountType: "EXPENSE",
        category: "COGS - Vaccine",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-100",
      },
      {
        accountCode: "5-200",
        accountName: "Beban Operasional",
        accountType: "EXPENSE",
        category: "Operating Expense",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 2,
        parentCode: "5-000",
      },
      {
        accountCode: "5-201",
        accountName: "Beban Gaji & Upah",
        accountType: "EXPENSE",
        category: "Salary Expense",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-202",
        accountName: "Beban Sewa",
        accountType: "EXPENSE",
        category: "Rent Expense",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-203",
        accountName: "Beban Listrik & Air",
        accountType: "EXPENSE",
        category: "Utilities",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-204",
        accountName: "Beban Telepon & Internet",
        accountType: "EXPENSE",
        category: "Communication",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-205",
        accountName: "Beban Supplies Kantor",
        accountType: "EXPENSE",
        category: "Office Supplies",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-206",
        accountName: "Beban Pemeliharaan & Perbaikan",
        accountType: "EXPENSE",
        category: "Maintenance",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-207",
        accountName: "Beban Transportasi",
        accountType: "EXPENSE",
        category: "Transportation",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-208",
        accountName: "Beban Marketing & Promosi",
        accountType: "EXPENSE",
        category: "Marketing",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-209",
        accountName: "Beban Asuransi",
        accountType: "EXPENSE",
        category: "Insurance",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-210",
        accountName: "Beban Penyusutan",
        accountType: "EXPENSE",
        category: "Depreciation",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-211",
        accountName: "Beban Administrasi Bank",
        accountType: "EXPENSE",
        category: "Bank Fees",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-212",
        accountName: "Beban Lain-lain",
        accountType: "EXPENSE",
        category: "Other Expense",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-200",
      },
      {
        accountCode: "5-300",
        accountName: "Beban Pajak",
        accountType: "EXPENSE",
        category: "Tax Expense",
        normalBalance: "DEBIT",
        isHeader: true,
        level: 2,
        parentCode: "5-000",
      },
      {
        accountCode: "5-301",
        accountName: "PPN Masukan",
        accountType: "EXPENSE",
        category: "VAT Input",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-300",
        taxable: true,
        description: "PPN dari pembelian",
      },
      {
        accountCode: "5-302",
        accountName: "Beban Pajak Penghasilan",
        accountType: "EXPENSE",
        category: "Income Tax",
        normalBalance: "DEBIT",
        isHeader: false,
        level: 3,
        parentCode: "5-300",
      },
    ];

    // Create accounts in order (parents first)
    const accountMap = new Map<string, string>(); // code -> id

    for (const account of accounts) {
      const parentAccountId = account.parentCode
        ? accountMap.get(account.parentCode)
        : undefined;

      const accountId = await ctx.db.insert("accounts", {
        accountCode: account.accountCode,
        accountName: account.accountName,
        accountType: account.accountType as any,
        category: account.category,
        parentAccountId: parentAccountId as any,
        normalBalance: account.normalBalance as "DEBIT" | "CREDIT",
        description: account.description,
        isHeader: account.isHeader,
        isActive: true,
        level: account.level,
        taxable: account.taxable,
        createdBy: undefined,
      });

      accountMap.set(account.accountCode, accountId);
    }

    return {
      message: `Successfully seeded ${accounts.length} accounts`,
      accountCount: accounts.length,
    };
  },
});
